CREATE TABLE IF NOT EXISTS users (
    Id SERIAL PRIMARY KEY,
    Email VARCHAR(200) UNIQUE NOT NULL,
    Password VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS ads (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Text TEXT NOT NULL,
    ImageURL VARCHAR(255),
    Price INT NOT NULL
);